#!/bin/sh

# Clean up cached files left behind by any previous containers using a background
# job if ${RASTER_BASE_DIR} is volume mounted on the host
if [ -d "${RASTER_BASE_DIR}" ]; then
	(
		# Select only the subfolders of ${RASTER_BASE_DIR}
		for dir in "${RASTER_BASE_DIR}"/*/; do
			# ${dir} will contain a trailing slash
			if [ -f "${dir}container_stopped" ]; then
				# First remove any temp files from the folder
				find "${dir}" -mindepth 1 -type f ! -name "container_stopped" -delete && \
				# Then remove the folder itself
				rm -r "${dir}"
			fi
		done
	) &
else
	echo "Error: Folder '${RASTER_BASE_DIR}' wasn't volume mounted on the host"
	return 1
fi

# Namespace the lazyraster cache folder using the container ID, which we read from ${HOSTNAME}
# This is needed because multiple lazyraster containers can run on the same machine.
export RASTER_BASE_DIR="${RASTER_BASE_DIR}/${HOSTNAME}"
mkdir -p ${RASTER_BASE_DIR}

echo "Launching Lazyraster service..."
/lazyraster/lazyraster
