on:
  push:
    branches:
      - "**"
      - "!main"

name: Snyk Security Check
jobs:
  security:
    name: security check
    runs-on: [self-hosted, linux, x64]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        with:
          args: snyk config set endpoint=https://app.eu.snyk.io/api
          command: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        
